[project]
name = "ceslib"
version = "0.1.0"
description = "CES core library"
readme = "README.md"
authors = [{ name = "Joao Eduardo Luis", email = "joao@clyso.com" }]
requires-python = ">=3.13"
dependencies = [
    "aioboto3==13.3.0",
    "hvac>=2.3.0",
    "pydantic>=2.11.6",
    "types-aioboto3[full]==13.3.0.post1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
