[project]
name = "crt"
version = "0.1.0"
description = "Ceph Release Tool"
authors = [{ name = "Joao Eduardo Luis", email = "joao@clyso.com" }]
requires-python = ">=3.13"
dependencies = [
    "click>=8.1.8",
    "gitpython>=3.1.44",
    "httpx>=0.28.1",
    "pydantic>=2.10.6",
]
